//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from the EF-PCOC T4 template v0.1.
//     Generation date: 04.06.2013 09:43:46
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace OrderManagement.DTO
{
	
	#region Entities
	
	
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		#region Property Change Event Handling
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		public event PropertyChangingEventHandler PropertyChanging;
		public event PropertyChangedEventHandler PropertyChanged;
		
		public void SendPropertyChanging()
		{
			if (PropertyChanging != null) {
				PropertyChanging(this, emptyChangingEventArgs);
			}
		}
			
		public void SendPropertyChanged(String propertyName)
		{
			if (PropertyChanged != null) {
				PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		#endregion
		
		#region Scalar Properties

		partial void OnCustomerIDChanging(string value);
		partial void OnCustomerIDChanged();

		private string _CustomerID;
		public string CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				this.OnCustomerIDChanging(value);
				this.SendPropertyChanging();
				this._CustomerID = value;
				this.SendPropertyChanged("CustomerID");
				this.OnCustomerIDChanged();
			}
		}
		
		partial void OnCompanyNameChanging(string value);
		partial void OnCompanyNameChanged();

		private string _CompanyName;
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				this.OnCompanyNameChanging(value);
				this.SendPropertyChanging();
				this._CompanyName = value;
				this.SendPropertyChanged("CompanyName");
				this.OnCompanyNameChanged();
			}
		}
		
		partial void OnContactNameChanging(string value);
		partial void OnContactNameChanged();

		private string _ContactName;
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				this.OnContactNameChanging(value);
				this.SendPropertyChanging();
				this._ContactName = value;
				this.SendPropertyChanged("ContactName");
				this.OnContactNameChanged();
			}
		}
		
		partial void OnContactTitleChanging(string value);
		partial void OnContactTitleChanged();

		private string _ContactTitle;
		public string ContactTitle
		{
			get
			{
				return this._ContactTitle;
			}
			set
			{
				this.OnContactTitleChanging(value);
				this.SendPropertyChanging();
				this._ContactTitle = value;
				this.SendPropertyChanged("ContactTitle");
				this.OnContactTitleChanged();
			}
		}
		
		partial void OnAddressChanging(string value);
		partial void OnAddressChanged();

		private string _Address;
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
		
		partial void OnCityChanging(string value);
		partial void OnCityChanged();

		private string _City;
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
		
		partial void OnRegionChanging(string value);
		partial void OnRegionChanged();

		private string _Region;
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				this.OnRegionChanging(value);
				this.SendPropertyChanging();
				this._Region = value;
				this.SendPropertyChanged("Region");
				this.OnRegionChanged();
			}
		}
		
		partial void OnPostalCodeChanging(string value);
		partial void OnPostalCodeChanged();

		private string _PostalCode;
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				this.OnPostalCodeChanging(value);
				this.SendPropertyChanging();
				this._PostalCode = value;
				this.SendPropertyChanged("PostalCode");
				this.OnPostalCodeChanged();
			}
		}
		
		partial void OnCountryChanging(string value);
		partial void OnCountryChanged();

		private string _Country;
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
		
		partial void OnPhoneChanging(string value);
		partial void OnPhoneChanged();

		private string _Phone;
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
		
		partial void OnFaxChanging(string value);
		partial void OnFaxChanged();

		private string _Fax;
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				this.OnFaxChanging(value);
				this.SendPropertyChanging();
				this._Fax = value;
				this.SendPropertyChanged("Fax");
				this.OnFaxChanged();
			}
		}
		
		#endregion

		#region Navigation Properties
	
		private ICollection<Order> _Orders;
		public ICollection<Order> Orders
		{
			get { return this._Orders; }
			set { this._Orders = value; }
		}

		#endregion
		
	}
	
	
	public partial class Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		#region Property Change Event Handling
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		public event PropertyChangingEventHandler PropertyChanging;
		public event PropertyChangedEventHandler PropertyChanged;
		
		public void SendPropertyChanging()
		{
			if (PropertyChanging != null) {
				PropertyChanging(this, emptyChangingEventArgs);
			}
		}
			
		public void SendPropertyChanged(String propertyName)
		{
			if (PropertyChanged != null) {
				PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		#endregion
		
		#region Scalar Properties

		partial void OnOrderIDChanging(int value);
		partial void OnOrderIDChanged();

		private int _OrderID;
		public int OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				this.OnOrderIDChanging(value);
				this.SendPropertyChanging();
				this._OrderID = value;
				this.SendPropertyChanged("OrderID");
				this.OnOrderIDChanged();
			}
		}
		
		partial void OnEmployeeIDChanging(int? value);
		partial void OnEmployeeIDChanged();

		private int? _EmployeeID;
		public int? EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				this.OnEmployeeIDChanging(value);
				this.SendPropertyChanging();
				this._EmployeeID = value;
				this.SendPropertyChanged("EmployeeID");
				this.OnEmployeeIDChanged();
			}
		}
		
		partial void OnOrderDateChanging(DateTime? value);
		partial void OnOrderDateChanged();

		private DateTime? _OrderDate;
		public DateTime? OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				this.OnOrderDateChanging(value);
				this.SendPropertyChanging();
				this._OrderDate = value;
				this.SendPropertyChanged("OrderDate");
				this.OnOrderDateChanged();
			}
		}
		
		partial void OnRequiredDateChanging(DateTime? value);
		partial void OnRequiredDateChanged();

		private DateTime? _RequiredDate;
		public DateTime? RequiredDate
		{
			get
			{
				return this._RequiredDate;
			}
			set
			{
				this.OnRequiredDateChanging(value);
				this.SendPropertyChanging();
				this._RequiredDate = value;
				this.SendPropertyChanged("RequiredDate");
				this.OnRequiredDateChanged();
			}
		}
		
		partial void OnShippedDateChanging(DateTime? value);
		partial void OnShippedDateChanged();

		private DateTime? _ShippedDate;
		public DateTime? ShippedDate
		{
			get
			{
				return this._ShippedDate;
			}
			set
			{
				this.OnShippedDateChanging(value);
				this.SendPropertyChanging();
				this._ShippedDate = value;
				this.SendPropertyChanged("ShippedDate");
				this.OnShippedDateChanged();
			}
		}
		
		partial void OnShipViaChanging(int? value);
		partial void OnShipViaChanged();

		private int? _ShipVia;
		public int? ShipVia
		{
			get
			{
				return this._ShipVia;
			}
			set
			{
				this.OnShipViaChanging(value);
				this.SendPropertyChanging();
				this._ShipVia = value;
				this.SendPropertyChanged("ShipVia");
				this.OnShipViaChanged();
			}
		}
		
		partial void OnFreightChanging(decimal? value);
		partial void OnFreightChanged();

		private decimal? _Freight;
		public decimal? Freight
		{
			get
			{
				return this._Freight;
			}
			set
			{
				this.OnFreightChanging(value);
				this.SendPropertyChanging();
				this._Freight = value;
				this.SendPropertyChanged("Freight");
				this.OnFreightChanged();
			}
		}
		
		partial void OnShipNameChanging(string value);
		partial void OnShipNameChanged();

		private string _ShipName;
		public string ShipName
		{
			get
			{
				return this._ShipName;
			}
			set
			{
				this.OnShipNameChanging(value);
				this.SendPropertyChanging();
				this._ShipName = value;
				this.SendPropertyChanged("ShipName");
				this.OnShipNameChanged();
			}
		}
		
		partial void OnShipAddressChanging(string value);
		partial void OnShipAddressChanged();

		private string _ShipAddress;
		public string ShipAddress
		{
			get
			{
				return this._ShipAddress;
			}
			set
			{
				this.OnShipAddressChanging(value);
				this.SendPropertyChanging();
				this._ShipAddress = value;
				this.SendPropertyChanged("ShipAddress");
				this.OnShipAddressChanged();
			}
		}
		
		partial void OnShipCityChanging(string value);
		partial void OnShipCityChanged();

		private string _ShipCity;
		public string ShipCity
		{
			get
			{
				return this._ShipCity;
			}
			set
			{
				this.OnShipCityChanging(value);
				this.SendPropertyChanging();
				this._ShipCity = value;
				this.SendPropertyChanged("ShipCity");
				this.OnShipCityChanged();
			}
		}
		
		partial void OnShipRegionChanging(string value);
		partial void OnShipRegionChanged();

		private string _ShipRegion;
		public string ShipRegion
		{
			get
			{
				return this._ShipRegion;
			}
			set
			{
				this.OnShipRegionChanging(value);
				this.SendPropertyChanging();
				this._ShipRegion = value;
				this.SendPropertyChanged("ShipRegion");
				this.OnShipRegionChanged();
			}
		}
		
		partial void OnShipPostalCodeChanging(string value);
		partial void OnShipPostalCodeChanged();

		private string _ShipPostalCode;
		public string ShipPostalCode
		{
			get
			{
				return this._ShipPostalCode;
			}
			set
			{
				this.OnShipPostalCodeChanging(value);
				this.SendPropertyChanging();
				this._ShipPostalCode = value;
				this.SendPropertyChanged("ShipPostalCode");
				this.OnShipPostalCodeChanged();
			}
		}
		
		partial void OnShipCountryChanging(string value);
		partial void OnShipCountryChanged();

		private string _ShipCountry;
		public string ShipCountry
		{
			get
			{
				return this._ShipCountry;
			}
			set
			{
				this.OnShipCountryChanging(value);
				this.SendPropertyChanging();
				this._ShipCountry = value;
				this.SendPropertyChanged("ShipCountry");
				this.OnShipCountryChanged();
			}
		}
		
		#endregion

		#region Navigation Properties
	
		private Customer _Customer;
		public Customer Customer
		{
			get { return this._Customer; }
			set { this._Customer = value; }
		}

		#endregion
		
	}
	
	#endregion
	
}
	

